open:
  name: Open Door
  description: Open the power pet door
  target:
    entity:
      domain: powerpetdoor
  fields:
    hold:
      name: Hold
      description: Hold the door open (don't auto-close)
      required: false
      selector:
        boolean:

close:
  name: Close Door
  description: Close the power pet door
  target:
    entity:
      domain: powerpetdoor

toggle:
  name: Open or Close Door
  description: Open or Close the power pet door
  target:
    entity:
      domain: powerpetdoor
  fields:
    hold:
      name: Hold
      description: Hold the door open (don't auto-close) - open only
      required: false
      selector:
        boolean:

enable_sensor:
  name: Enable Sensor
  description: Enable the indoor or outdoor proximity sensors
  target:
    entity:
      domain: powerpetdoor
  fields:
    sensor:
      name: Sensor
      description: The sensor to enable (inside or outside)
      required: true
      selctor:
        select:
          options:
            - inside
            - outside

disable_sensor:
  name: Disable Sensor
  description: Disable the indoor or outdoor proximity sensors
  target:
    entity:
      domain: powerpetdoor
  fields:
    sensor:
      name: Sensor
      description: The sensor to disable (inside or outside)
      required: true
      selctor:
        select:
          options:
            - inside
            - outside

toggle_sensor:
  name: Toggle Sensor
  description: Toggle the indoor or outdoor proximity sensors
  target:
    entity:
      domain: powerpetdoor
  fields:
    sensor:
      name: Sensor
      description: The sensor to toggle (inside or outside)
      required: true
      selctor:
        select:
          options:
            - inside
            - outside

enable_auto:
  name: Enable Auto
  description: Enable automatic (scheduled) mode
  target:
    entity:
      domain: powerpetdoor

disable_auto:
  name: Disable Auto
  description: Disable automatic (scheduled) mode
  target:
    entity:
      domain: powerpetdoor

toggle_auto:
  name: Toggle Auto
  description: Toggle automatic (scheduled) mode
  target:
    entity:
      domain: powerpetdoor

power_on:
  name: Power On
  description: Power on the pet door
  target:
    entity:
      domain: powerpetdoor

power_off:
  name: Power Off
  description: Power of the pet door
  target:
    entity:
      domain: powerpetdoor

power_toggle:
  name: Toggle Power
  description: Toggle the pet door power
  target:
    entity:
      domain: powerpetdoor
