open:
  name: Open Door
  description: Open the power pet door
  target:
    entity:
      domain: switch
      integration: powerpetdoor
      device_class: door
  fields:
    hold:
      name: Hold
      description: Hold the door open (don't auto-close)
      required: false
      selector:
        boolean:

close:
  name: Close Door
  description: Close the power pet door
  target:
    entity:
      domain: switch
      integration: powerpetdoor
      device_class: door

toggle:
  name: Open or Close Door
  description: Open or Close the power pet door
  target:
    entity:
      domain: switch
      integration: powerpetdoor
      device_class: door
  fields:
    hold:
      name: Hold
      description: Hold the door open (don't auto-close) - open only
      required: false
      selector:
        boolean:
